name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Clonar el repositorio"
        uses: actions/checkout@v3

      - name: "Configurar Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: "Instalar dependencias"
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Ejecutar pruebas"
        run: |
          . venv/bin/activate
          pytest tests/
        env:
          PYTHONPATH: .

      - name: "Construir imagen Docker"
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
        env:
          DOCKER_BUILDKIT: 1

      - name: "Login en GitHub Container Registry"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Publicar imagen en GHCR"
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}